# Copyright (C) 2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/mobvoi/catfish/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/mobvoi/catfish/proprietary/lib/extractors/libaacextractor.so:system/lib/extractors/libaacextractor.so \
    vendor/mobvoi/catfish/proprietary/lib/extractors/libamrextractor.so:system/lib/extractors/libamrextractor.so \
    vendor/mobvoi/catfish/proprietary/lib/extractors/libflacextractor.so:system/lib/extractors/libflacextractor.so \
    vendor/mobvoi/catfish/proprietary/lib/extractors/libmidiextractor.so:system/lib/extractors/libmidiextractor.so \
    vendor/mobvoi/catfish/proprietary/lib/extractors/libmkvextractor.so:system/lib/extractors/libmkvextractor.so \
    vendor/mobvoi/catfish/proprietary/lib/extractors/libmp3extractor.so:system/lib/extractors/libmp3extractor.so \
    vendor/mobvoi/catfish/proprietary/lib/extractors/libmp4extractor.so:system/lib/extractors/libmp4extractor.so \
    vendor/mobvoi/catfish/proprietary/lib/extractors/libmpeg2extractor.so:system/lib/extractors/libmpeg2extractor.so \
    vendor/mobvoi/catfish/proprietary/lib/extractors/liboggextractor.so:system/lib/extractors/liboggextractor.so \
    vendor/mobvoi/catfish/proprietary/lib/extractors/libwavextractor.so:system/lib/extractors/libwavextractor.so \
    vendor/mobvoi/catfish/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/mobvoi/catfish/proprietary/lib/vendor.display.color@1.0.so:system/lib/vendor.display.color@1.0.so \
    vendor/mobvoi/catfish/proprietary/lib/vendor.display.postproc@1.0.so:system/lib/vendor.display.postproc@1.0.so \
    vendor/mobvoi/catfish/proprietary/vendor/bin/adsprpcd:system/vendor/bin/adsprpcd \
    vendor/mobvoi/catfish/proprietary/vendor/bin/irsc_util:system/vendor/bin/irsc_util \
    vendor/mobvoi/catfish/proprietary/vendor/bin/nanoapp_cmd:system/vendor/bin/nanoapp_cmd \
    vendor/mobvoi/catfish/proprietary/vendor/bin/nanoapp_hr_log:system/vendor/bin/nanoapp_hr_log \
    vendor/mobvoi/catfish/proprietary/vendor/bin/nanotool:system/vendor/bin/nanotool \
    vendor/mobvoi/catfish/proprietary/vendor/bin/netmgrd:system/vendor/bin/netmgrd \
    vendor/mobvoi/catfish/proprietary/vendor/bin/qseecomd:system/vendor/bin/qseecomd \
    vendor/mobvoi/catfish/proprietary/vendor/bin/qti:system/vendor/bin/qti \
    vendor/mobvoi/catfish/proprietary/vendor/bin/rmt_storage:system/vendor/bin/rmt_storage \
    vendor/mobvoi/catfish/proprietary/vendor/bin/tftp_server:system/vendor/bin/tftp_server \
    vendor/mobvoi/catfish/proprietary/vendor/bin/thermal-engine:system/vendor/bin/thermal-engine \
    vendor/mobvoi/catfish/proprietary/vendor/bin/time_daemon:system/vendor/bin/time_daemon \
    vendor/mobvoi/catfish/proprietary/vendor/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:system/vendor/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    vendor/mobvoi/catfish/proprietary/vendor/etc/acdbdata/MTP/MTP_General_cal.acdb:system/vendor/etc/acdbdata/MTP/MTP_General_cal.acdb \
    vendor/mobvoi/catfish/proprietary/vendor/etc/acdbdata/MTP/MTP_Handset_cal.acdb:system/vendor/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/mobvoi/catfish/proprietary/vendor/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:system/vendor/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    vendor/mobvoi/catfish/proprietary/vendor/etc/acdbdata/MTP/MTP_Headset_cal.acdb:system/vendor/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    vendor/mobvoi/catfish/proprietary/vendor/firmware/BCM43430B0.hcd:system/vendor/firmware/BCM43430B0.hcd \
    vendor/mobvoi/catfish/proprietary/vendor/firmware/a300_pfp.fw:system/vendor/firmware/a300_pfp.fw \
    vendor/mobvoi/catfish/proprietary/vendor/firmware/a300_pm4.fw:system/vendor/firmware/a300_pm4.fw \
    vendor/mobvoi/catfish/proprietary/vendor/firmware/fw_bcmdhd.bin:system/vendor/firmware/fw_bcmdhd.bin \
    vendor/mobvoi/catfish/proprietary/vendor/firmware/fw_bcmdhd_apsta.bin:system/vendor/firmware/fw_bcmdhd_apsta.bin \
    vendor/mobvoi/catfish/proprietary/vendor/firmware/it7259.cfg:system/vendor/firmware/it7259.cfg \
    vendor/mobvoi/catfish/proprietary/vendor/firmware/it7259.fw:system/vendor/firmware/it7259.fw \
    vendor/mobvoi/catfish/proprietary/vendor/firmware/nanohub.full.catshark.20033010.bin:system/vendor/firmware/nanohub.full.catshark.20033010.bin \
    vendor/mobvoi/catfish/proprietary/vendor/lib/egl/eglSubDriverAndroid.so:system/vendor/lib/egl/eglSubDriverAndroid.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/egl/libQTapGLES.so:system/vendor/lib/egl/libQTapGLES.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/egl/libq3dtools_esx.so:system/vendor/lib/egl/libq3dtools_esx.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/hw/nfc_nci.st21.default.so:system/vendor/lib/hw/nfc_nci.st21.default.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/hw/sensors.nanohub.so:system/vendor/lib/hw/sensors.nanohub.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libacdb-fts.so:system/vendor/lib/libacdb-fts.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libaudioalsa.so:system/vendor/lib/libaudioalsa.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libdisp-aba.so:system/vendor/lib/libdisp-aba.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libhubconnection.so:system/vendor/lib/libhubconnection.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libqcmaputils.so:system/vendor/lib/libqcmaputils.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libsdm-diag.so:system/vendor/lib/libsdm-diag.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libsdm-disp-vndapis.so:system/vendor/lib/libsdm-disp-vndapis.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libsdmcore.so:system/vendor/lib/libsdmcore.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libsdmextension.so:system/vendor/lib/libsdmextension.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libsubsystem_control.so:system/vendor/lib/libsubsystem_control.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/soundfx/libbundlewrapper.so:system/vendor/lib/soundfx/libbundlewrapper.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/soundfx/libdownmix.so:system/vendor/lib/soundfx/libdownmix.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/soundfx/libdynproc.so:system/vendor/lib/soundfx/libdynproc.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/soundfx/libeffectproxy.so:system/vendor/lib/soundfx/libeffectproxy.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/soundfx/libldnhncr.so:system/vendor/lib/soundfx/libldnhncr.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/soundfx/libqcompostprocbundle.so:system/vendor/lib/soundfx/libqcompostprocbundle.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/soundfx/libqcomvisualizer.so:system/vendor/lib/soundfx/libqcomvisualizer.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/soundfx/libqcomvoiceprocessing.so:system/vendor/lib/soundfx/libqcomvoiceprocessing.so \
    vendor/mobvoi/catfish/proprietary/vendor/lib/soundfx/libreverbwrapper.so:system/vendor/lib/soundfx/libreverbwrapper.so

PRODUCT_PACKAGES += \
    libtime_genoff \
    TimeService
